foodOnline_main/urls.py

from django.contrib import admin
from django.urls import path,include
from .import views	#. manje tyach directory madhe views aahe jya directory madhe urls aaeht
from django.conf import settings
from django.conf.urls.static import static
from marketplace import views as MarketplaceViews

urlpatterns = [
    path('admin/', admin.site.urls),
    path("",views.home,name="home"),	
    path("accounts/",include('accounts.urls')),

    path('marketplace/',include("marketplace.urls")),

    path('cart/', MarketplaceViews.cart,name='cart'),

    

    #checkout
    path('checkout/',MarketplaceViews.checkout,name='checkout'),

    #Orders
    path('orders/',include("orders.urls")),
    path('search/',MarketplaceViews.search,name="search"),
    
]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.urls import path
from . import views

urlpatterns =[
    path('place_order/',views.place_order,name="place_order"),
    path('payments/',views.payments,name="payments"),
    path('order_complete/',views.order_complete,name="order_complete"),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser,BaseUserManager
#from django.db.models.fields.related import ForeinKey,OneToOneField

from django.contrib.gis.db import models as gismodels
from django.contrib.gis.geos import Point





# Create your models here.
class UserManager(BaseUserManager): #usermanager manje tu customize database banavtoys jaasa ki hyat tula swataun create karava lagtay entry fields email,username,first name and all whereas User ha django by default support karta tyat already entry fields present aastat 
    def create_user(self,first_name,last_name,username,email,password=None):
        if not email:
            raise ValueError("User must have an email address")
        
        if not username:
            raise ValueError("User must have an username")
        
        user=self.model(
            email=self.normalize_email(email),  #email id uppercase takli tar lower madhe convert karnaar
            username=username,
            first_name=first_name,
            last_name=last_name,
        )
        user.set_password(password) #password la hash karnaar basically encode karnaar
        user.save(using=self._db)    #je settimgs madhe default database aahe toh ghenar configurations kelet tyala reference gheun save honaar data 
        return user

    def create_superuser(self,first_name,last_name,username,email,password=None):
        user=self.create_user(
            email=self.normalize_email(email),
            username=username,
	    password=password,	
            first_name=first_name,
            last_name=last_name,
        )
        user.is_admin=True
        user.is_active=True
        user.is_staff=True
        user.is_superadmin=True
        user.save(using=self._db)
        return user 

class User(AbstractBaseUser):   #this abstractbaseuser are used for modifying the customized models and also include the authentication which is supported by django .  
    VENDOR=1
    CUSTOMER=2

    ROLE_CHOICE=(
        (VENDOR,'Vendor'),
        (CUSTOMER,'Customer'),
    )
    first_name=models.CharField(max_length=50)
    last_name=models.CharField(max_length=50)
    username=models.CharField(max_length=50,unique=True)
    email=models.EmailField(max_length=100,unique=True)
    phone_no=models.CharField(max_length=12,blank=True,null=True)
    role=models.PositiveSmallIntegerField(choices=ROLE_CHOICE,blank=True,null=True)

    #required field
    date_joined=models.DateTimeField(auto_now_add=True)
    last_login=models.DateTimeField(auto_now_add=True)
    created_date=models.DateTimeField(auto_now_add=True)
    modified_date=models.DateTimeField(auto_now_add=True)
    is_admin=models.BooleanField(default=False)
    is_staff=models.BooleanField(default=False)
    is_active=models.BooleanField(default=False)
    is_superadmin=models.BooleanField(default=False)

    USERNAME_FIELD='email'  #hyat kadi pan django username je aasta te bydefault username mahnun gheto pan aaplya la email paije te set kelay
    REQUIRED_FIELDS=['username','first_name','last_name']

    objects = UserManager()

    def __str__(self):
        return self.email
    
    def has_perm(self,perm,obj=None):   #heh permission vale fakta admin ani super admin jeva active aasnar teva true aasnar baki normal user sathi false
        return self.is_admin
    
    def has_module_perms(self,app_label):
        return True
    
    def get_role(self):
        if self.role == 1:
            user_role = 'Vendor'
        elif self.role == 2:
            user_role = 'Customer'
        return user_role    


    

class userprofile(models.Model):
    user=models.OneToOneField(User,on_delete=models.CASCADE,blank=True,null=True)  #hyat na one to one field vaparli aahe karanki one user can have only one user profile aani tyala varcha User chya table la link kelay on_delete manje profile delete jhala tar user che sagle details delete hoyayla paije,blank ani null aasach lilay kahi error nahi dila paije mahnun     
    profile_picture=models.ImageField(upload_to='users/profile_picures',blank=True,null=True)
    cover_photo=models.ImageField(upload_to='users/cover_photos',blank=True,null=True)
    address=models.CharField(max_length=250,blank=True,null=True)
    
    country=models.CharField(max_length=15,blank=True,null=True)
    state=models.CharField(max_length=15,blank=True,null=True)
    city=models.CharField(max_length=15,blank=True,null=True)
    pin_code=models.CharField(max_length=6,blank=True,null=True)
    latitude=models.CharField(max_length=20,blank=True,null=True)
    longitude=models.CharField(max_length=20,blank=True,null=True)
    location=gismodels.PointField(blank=True,null=True,srid=4326)
    created_at=models.DateTimeField(auto_now_add=True)
    modified_at=models.DateTimeField(auto_now=True)

    #def full_address(self):
       # return f'{self.address_line_1},{self.address_line_2}'
    def __str__(self):
        return self.user.email  #heh User chya mail la call kelay


    def save(self, *args, **kwargs):
        if self.latitude and self.longitude:
            self.location=Point(float(self.longitude),float(self.latitude))
            return super(userprofile,self).save(*args,**kwargs)
        return super(userprofile,self).save(*args,**kwargs)

orders/models.py
import json
from django.db import models
from accounts.models import User
from menu.models import FoodItem
from vendor.models import Vendor

request_object=''

class Payment(models.Model):
    PAYMENT_METHOD=(
        ('PayPal','PayPal'),
        ('RazorPay','RazorPay'),#Only for Indian Students.
    )
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    transaction_id=models.CharField(max_length=100)
    payment_method=models.CharField(choices=PAYMENT_METHOD,max_length=100)
    amount=models.CharField(max_length=10)
    status=models.CharField(max_length=100)
    created_at=models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.transaction_id
    
class Order(models.Model):
    STATUS=(
        ('New','New'),
        ('Accepted','Accepted'),
        ('Completed','Completed'),
        ('Cancelled','Cancelled'),
    )

    user=models.ForeignKey(User,on_delete=models.SET_NULL,null=True)
    payment=models.ForeignKey(Payment,on_delete=models.SET_NULL,blank=True,null=True)
    vendors=models.ManyToManyField(Vendor,blank=True)
    order_number=models.CharField(max_length=20)
    first_name=models.CharField(max_length=50)
    last_name=models.CharField(max_length=50)
    phone_no=models.CharField(max_length=15,blank=True)
    email=models.EmailField(max_length=50)
    address=models.CharField(max_length=200)
    country=models.CharField(max_length=15,blank=True)
    state=models.CharField(max_length=15,blank=True)
    city=models.CharField(max_length=50)
    pin_code=models.CharField(max_length=10)
    total=models.FloatField()
    tax_data=models.JSONField(blank=True,help_text="Data format: {'tax_type':{'tax_percentage':'tax_amount'}}",null=True)
    total_data=models.JSONField(blank=True,null=True)
    total_tax=models.FloatField()
    payment_method=models.CharField(max_length=25)
    status=models.CharField(max_length=15,choices=STATUS,default='New')
    is_ordered=models.BooleanField(default=False)
    created_at=models.DateTimeField(auto_now_add=True)
    updated_at=models.DateTimeField(auto_now=True)

    #concatenate first and last name
    @property
    def name(self):
        return f'{self.first_name} {self.last_name}'
    
    def order_placed_to(self):
        return ", ".join([str(i) for i in self.vendors.all()])
    
    def get_total_by_vendor(self):
        vendor=Vendor.objects.get(user=request_object.user)
        subtotal=0
        tax=0
        tax_dict={}

        if self.total_data:
            total_data=json.loads(self.total_data)
            data=total_data.get(str(vendor.id))


            for key,val in data.items():
                subtotal += float(key)
                val=val.replace("'",'"')
                val=json.loads(val)
                tax_dict.update(val)

                #calculate tax
                #{'CGST':{'9.00':'6.03'},'SGST':{'7.00':'4.69'}}
                for i in val:
                    for j in val[i]:
                        tax+=float(val[i][j])
        grand_total=float(subtotal)+float(tax)
        
        
        context={
            'subtotal':subtotal,
            'tax_dict':tax_dict,
            'grand_total':grand_total,
        }
        return context

    def __str__(self):
        return self.order_number    
    


class OrderedFood(models.Model):
    order=models.ForeignKey(Order,on_delete=models.CASCADE)
    payment=models.ForeignKey(Payment,on_delete=models.SET_NULL,blank=True,null=True)
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    fooditem=models.ForeignKey(FoodItem,on_delete=models.CASCADE)
    quantity=models.IntegerField()
    price=models.FloatField()
    amount=models.FloatField()
    created_at=models.DateTimeField(auto_now_add=True)
    updated_at=models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.fooditem.food_title
    
# Create your models here.

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>FoodOnline</title>
	<!-- Google Font Family Link Start -->
	<link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Montserrat:400,700">
	<link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Open+Sans:400,700,800">
	<!-- Google Font Family Link End -->

	<!-- CSS -->
	<link href="{% static 'css/iconmoon.css' %}" rel="stylesheet">
	<link href="{% static 'css/style.css' %}" rel="stylesheet">
	<link href="{% static 'css/cs-foodbakery-plugin.css' %}" rel="stylesheet">
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
	<link href="{% static 'css/bootstrap-slider.css' %}" rel="stylesheet">

	<!--Awsome Fonts je aapan + vagere dakavtaoy na add food or category in menu tyachya css la heh load kartay-->
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
	
	<!-- JAVASCRIPT -->
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
	<script src="{% static 'js/modernizr.js' %}"></script>
	<script src="{% static 'js/bootstrap.js' %}"></script>

	<link rel="stylesheet" href="{% static 'css/custom.css' %}">

	

	<script src="https://maps.googleapis.com/maps/api/js?key={{GOOGLE_API_KEY}}&libraries=places&callback=initAutoComplete" defer></script>
	<script src="{% static 'js/custom.js' %}"></script>
	<!--<link rel="stylesheet" href="{% static 'js/custom.js' %}">-->
	
	<script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
	<script src="{% static 'js/custom.js' %}"></script>

	<!-- include datatables plugin script and css -->
	 <link rel="stylesheet" href="//cdn.datatables.net/2.1.8/css/dataTables.dataTables.min.css">
	 <script src="//cdn.datatables.net/2.1.8/js/dataTables.min.js"></script>
	 <script>
		$(document).ready(function (){
			$('#myOrdersTable').DataTable();
		});
	 </script>
	<style>
		body, .main-section p, .mce-content-body p{
			font:Normal  14px/24px "Open Sans", sans-serif;letter-spacing: 0px;text-transform: none;color: #515151 !important;
		}
	</style>
</head>

<body>

	<!-- LOAD NAVBAR HERE-->
	{% include 'includes/navbar.html' %}

	<!-- LOAD CONTENT-->
	{% block content %}
	<!-- CONTENT GOES HERE -->
	 {% endblock %}

	<!--LOAD FOOTER-->
	{% include 'includes/footer.html' %}
	<!--Main Wrapper-->
	
	
		
</body>

</html>

templates/home.html
{% extends 'base.html' %}
{% load static %}
	<!-- Main Section Start -->
{% block content %}
	<div class="main-section">
		<!-- Home Pages Elements Strat -->
		<!-- Main Search Start -->
		<div class="page-section nopadding cs-nomargin" style="padding-top: 200px; padding-bottom: 150px; margin-bottom: 0px; background: url(static/extra-images/bg-image1.jpg) no-repeat center / cover;">
			<div class="container">
				<div class="row">
					<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 ">
						<div class="element-title">
							<h1 style="font-size: 40px; color: #505050; text-transform: uppercase; line-height: 50px; margin-bottom: 25px; text-align:center;">
								Empowering Local Flavors, One Bite at a Time</h1>
							<p style="font-size: 18px; letter-spacing: 1px; color: #505050; text-align:center;">
								</p>
						</div>
					</div>
					<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 ">
						<div class="main-search fancy bg-holder">
							<form action="{% url 'search' %}" method="GET">
								<div class="row">
									<div class="col-lg-4 col-md-4 col-sm-3 col-xs-12">
										<div class="field-holder">
											<input type="text"  name ="keyword" placeholder="Resturant name or Food Name">
										</div>
									</div>
									<div class="col-lg-4 col-md-4 col-sm-5 col-xs-12">
										<div class="field-holder">
											<ul>
												<li class="select-location">
													<div class="foodbakery-locations-fields-group foodbakery-focus-out">
														<span class="foodbakery-search-location-icon"><i class="icon-location"></i></span>
														
														<input type="text" name="address" class="location-field-text filter" id="id_address" required placeholder="All Locations">
														<input type="hidden" name="lat" val="" id="id_latitude">
														<input type="hidden" name="lng" val="" id="id_longitude">
													</div>
												</li>
											</ul>
										</div>
									</div>

									<div class="col-lg-2 col-md-2 col-sm-2 col-xs-12">
										<select name="radius" id="radius" style="height:50px;" required>
											<option value="" selected>Choose Radius</option>
											<option value="1">1km</option>
											<option value="3">3km</option>
											<option value="5">5km</option>
											<option value="7">7km</option>
											<option value="10">10km</option>

										</select>
									</div>
									

									<div class="col-lg-2 col-md-2 col-sm-2 col-xs-12">
										<div class="field-holder">
											<input type="submit" value="Search">
										</div>
									</div>
								</div>
							</form>
						</div>
					</div>
					
				</div>
			</div>
		</div>
		<!-- Main Search End -->
		
		<!-- Top Restarurants Section Start -->
		<div class="page-section nopadding cs-nomargin" style="margin-top: 0px;padding-top: 60px;padding-bottom: 0px;margin-bottom: 0px;background: #ffffff;">
			<div class="container">
				<div class="row">
					<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
						<div class="element-title align-left">
							<h2>Top Restaurants</h2>
							<p>Explore restaurants, bars, and cafés by locality</p>
						</div>
					</div>
					<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12" style="padding-right:0 !important;padding-left:0 !important;">
						<div class="company-logo">
							<ul>
								{% for vendor in vendors %}
								<li class="has-border">
									<figure>
										{% if vendor.user_profile.profile_picture %}
											<a href="{% url 'vendor_detail' vendor.vendor_slug %}"><img src="{{ vendor.user_profile.profile_picture.url }}" class="attachment-full size-full wp-post-image" alt=""></a>
										{% else %}
											<a href="{% url 'vendor_detail' vendor.vendor_slug %}"><img src="{% static 'images/default-profile.png' %}" class="attachment-full size-full wp-post-image" alt=""></a>
										{% endif %}
									</figure>
								</li>
								{% endfor %}
							</ul>
						</div>
					</div>
				</div>
			</div>
		</div>
		<!-- Top Restarurants Section End -->
		<!-- Choose From Most Popular Listin Start -->
		<div class="page-section nopadding cs-nomargin" style="margin-top: 0px;padding-top: 60px;padding-bottom: 50px;margin-bottom: 0px;background: #ffffff;">
			<div class="container">
				<div class="row">
					<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
						<div class="element-title align-center">
							<h2>Choose From Most Popular Restaurants</h2>
							<p>Here are some most search restaurants</p>
						</div>
					</div>
					<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
						<div class="listing fancy">
							<ul class="row">
								{% for vendor in vendors %}
								<li class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
									<div class="list-post featured">
										<div class="img-holder">
											<figure>
												<a href="{% url 'vendor_detail' vendor.vendor_slug %}">
													{% if vendor.user_profile.profile_picture %}
														<img src="{{ vendor.user_profile.profile_picture.url }}" class="img-thumb wp-post-image" alt="">
													{% else %}
														<img src="{% static 'images/default-profile.png' %}" class="img-thumb wp-post-image" alt="">
													{% endif %}
												</a>
											</figure>
											<span class="restaurant-status open">
												<em class="bookmarkRibbon"></em>Open
											</span>
										</div>
										<div class="text-holder">
											
											<div class="post-title">
												<h5>
													<a href="{% url 'vendor_detail' vendor.vendor_slug %}">{{ vendor }}</a>
													
												</h5>
											</div>
											{% if vendor.user_profile.city and vendor.user_profile.state and vendor.user_profile.pin_code %}
												<span>{{ vendor.user_profile.city }},{{ vendor.user_profile.state }},{{ vendor.user_profile.pin_code }}</span>
											{% endif %}
											
											{% if vendor.kms %}
												<br>
												<span><small><b>{{vendor.kms}} km </b>away</small></span>
											{% endif %}
										</div>
										
									</div>
								</li>
								{% endfor %}
							</ul>
						</div>
					</div>
				</div>
			</div>
		</div>
		<!-- Choose From Most Popular Listing End -->

		<!-- Home Pages Elements End  -->
	</div>
	<!-- Main Section End -->
{% endblock %}